# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:42:04+00:00

from __future__ import annotations

from pydantic import BaseModel


class AssetGetResponse(BaseModel):
    pass


class AssetAssetIdGetResponse(BaseModel):
    pass


class AssetAssetIdContributorGetResponse(BaseModel):
    pass


class CatalogueGetResponse(BaseModel):
    pass


class CatalogueCatalogueIdGetResponse(BaseModel):
    pass


class CatalogueCatalogueIdAssetGetResponse(BaseModel):
    pass


class CatalogueCatalogueIdAssetAssetIdGetResponse(BaseModel):
    pass


class ChannelGetResponse(BaseModel):
    pass


class ChannelChannelIdGetResponse(BaseModel):
    pass


class ContributorGetResponse(BaseModel):
    pass


class ContributorContributorIdGetResponse(BaseModel):
    pass


class FeatureGetResponse(BaseModel):
    pass


class FeatureTypeGetResponse(BaseModel):
    pass


class FeatureFeatureIdGetResponse(BaseModel):
    pass


class PlatformGetResponse(BaseModel):
    pass


class PlatformPlatformIdGetResponse(BaseModel):
    pass


class PlatformPlatformIdRegionGetResponse(BaseModel):
    pass


class ScheduleGetResponse(BaseModel):
    pass
